solutions 5
js-tasks-ru/vue-20200615_voljgm pull request #8
Opened 2020-07-26 13:05 UTC by volj1

2020-07-26 13:11 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
AppInput
+ AppInput должен иметь параметры small, rounded и multiline
+ AppInput должен рендерить поле ввода form-control внутри input-group
+ AppInput должен иметь класс form-control_sm только с параметром small
+ AppInput должен иметь класс form-control_rounded только с параметром rounded
+ AppInput должен рендерить многострочное поле ввода с параметром multiline
+ Параметры small и rounded также работают с многострочным AppInput
+ AppInput должен принимать различные атрибуты полей ввода
+ AppInput должен принимать различные атрибуты полей ввода для textarea
+ AppInput должен рендерить корректный тип input (password)
+ AppInput должен рендерить корректный тип input (num)
+ AppInput должен рендерить корректный тип input (range)
+ AppInput должен рендерить корректный тип input (date)
+ AppInput должен рендерить корректный тип input (time)
+ AppInput должен рендерить корректный тип input (email)
+ AppInput должен рендерить корректный тип input (tel)
+ AppInput должен выводить текущее значение (multiline=false)
+ AppInput должен выводить текущее значение (multiline=true)
+ AppInput должен обрабатывать нативный ввод и порождать input, change с введённым значением
+ AppInput должен выводить левую иконку и добавлять классы input-group_icon input-group_icon-left
+ AppInput должен выводить правую иконку и добавлять классы input-group_icon input-group_icon-right
```
```diff
Buttons
+ Компонент BaseButton должен иметь логический параметр block
+ Компонент BaseButton должен иметь необязательный строковый параметр tag со значением button по умолчанию
+ Параметр tag у BaseButton должен иметь валидатор
+ Компонент BaseButton должен рендерить своё содержимое
+ Компонент BaseButton не должен иметь класс button_block
+ Компонент BaseButton должен иметь класс button_block с параметром block
+ Компонент BaseButton должен рендерить ссылку с tag=a
+ Компонент BaseButton должен рендерить ссылку с tag=a c переданными href и target
+ Компонент BaseButton должен обрабатывать нативный клик
+ Компонент PrimaryButton должен рендерить компонент BaseButton с тем же содержимым
+ Компонент PrimaryButton должен рендерить кнопку с классом button_primary
+ Компонент SecondaryButton должен рендерить компонент BaseButton с тем же содержимым
+ Компонент SecondaryButton должен рендерить кнопку с классом button_secondary
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-07-28 04:44 UTC, ShGKme requested changes
Задача 5-2 принята.
Задача 5-3 не принята, так как компонент не является прозрачной обёрткой `TransparentWrapper`. Он не проксирует нативные события, и нельзя установить такие события, как `focus`, например.

2020-07-28 12:03 UTC, jsru commented
@ShGKme ping :)

2020-07-28 12:08 UTC, ShGKme requested changes

2020-07-28 12:08 UTC, ShGKme commented on 5-module/3-task/components/AppInput.vue
>      }
Это лучше сделать вычисляемым свойством, а не методом, не создавая каждый раз новый набор обработчиков при ререндеринге.

Кроме того, с использованием современного (2015+) синтаксиса, код можно сделать проще, без использования `vm = this`.
```javascript
return {
  ...this.$listeners,
  input: ($event) => { 
    this.$emit('input', $event.target.value); 
  }
}
```

2020-07-28 12:14 UTC, ShGKme commented on 5-module/3-task/components/AppInput.vue
>      }
Не туда посмотрел, это итак вычисляемое свойство, а не метод

2020-07-28 12:16 UTC, ShGKme commented on 5-module/3-task/components/AppInput.vue
> +  },
Компонент работает, но усложнён. Предлагается переделать его в классический `TransparentWrapper` компонент, убрал локальное свойство.

2020-07-28 12:32 UTC, ShGKme approved these changes
Принято 👍

2020-07-28 12:32 UTC, merged